# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'int_gra.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 233)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_activar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_activar.setGeometry(QtCore.QRect(30, 50, 111, 51))
        self.boton_activar.setObjectName("boton_activar")
        self.boton_desactivar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_desactivar.setGeometry(QtCore.QRect(220, 50, 111, 51))
        self.boton_desactivar.setObjectName("boton_desactivar")
        self.etiqueta = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta.setGeometry(QtCore.QRect(30, 130, 311, 31))
        self.etiqueta.setText("")
        self.etiqueta.setAlignment(QtCore.Qt.AlignCenter)
        self.etiqueta.setObjectName("etiqueta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_activar.setText(_translate("MainWindow", "ACTIVAR"))
        self.boton_desactivar.setText(_translate("MainWindow", "DESACTIVAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
